In [2]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sympy as sp

In [15]:
sp.init_printing()
m = 4
n = 6

A = np.random.randn(m, n)

# Matrix rank
ra = np.linalg.matrix_rank(A)
print('Rank = {}'.format(ra))

print(A), print('')

# Set last column to repeat of penultimate column
B = A
B[:, -1] = B[:, -2]
print(B), print('')
rb = np.linalg.matrix_rank(B)
print('Rank = {}'.format(rb))  # As rank is min(m, n)

# Set last row to repeat of penultimate row
C = A
C[-1, :] = A[-2, :]
print(C), print('')
rc = np.linalg.matrix_rank(C)
print('Rank = {}'.format(rc))  # As rank is number of independent rows or cols

Rank = 4
[[ 1.28170732 -2.45868759 -1.38405071 -1.41228    -0.0623647   1.17086931]
 [ 0.11111811  0.03608222 -1.05482184  1.97667322 -0.35773095 -0.25134685]
 [-0.7435854  -0.38869538  1.89554538  0.23915436  0.81312287 -0.7890655 ]
 [-0.88521355 -1.06203956 -1.58951002  1.14928125 -0.11425925  0.51386722]]

[[ 1.28170732 -2.45868759 -1.38405071 -1.41228    -0.0623647  -0.0623647 ]
 [ 0.11111811  0.03608222 -1.05482184  1.97667322 -0.35773095 -0.35773095]
 [-0.7435854  -0.38869538  1.89554538  0.23915436  0.81312287  0.81312287]
 [-0.88521355 -1.06203956 -1.58951002  1.14928125 -0.11425925 -0.11425925]]

Rank = 4
[[ 1.28170732 -2.45868759 -1.38405071 -1.41228    -0.0623647  -0.0623647 ]
 [ 0.11111811  0.03608222 -1.05482184  1.97667322 -0.35773095 -0.35773095]
 [-0.7435854  -0.38869538  1.89554538  0.23915436  0.81312287  0.81312287]
 [-0.7435854  -0.38869538  1.89554538  0.23915436  0.81312287  0.81312287]]

Rank = 3


In [17]:
# Adding noise to see effect on rank - increases the rank

A = np.round(10*np.random.randn(m, m))

# Reduce the rank
A[:, -1] = A[:, -2]

# Add noise
noise = .001
B = A + noise*np.random.randn(m, m)

print('Rank without noise: {}'.format(np.linalg.matrix_rank(A)))
print('Rank with noise: {}'.format(np.linalg.matrix_rank(B)))

Rank without noise: 3
Rank with noise: 4


In [20]:
# Rank of added and multiplied matrix
# Rank(A+B) <= Rank(A) + Rank(B)
# Rank(AB) <= min(rank(A), rank(B))

# Redcued rank matrix using matrix multiplication

A = np.random.randn(10, 4)
B = np.random.randn(4, 10)
C = A@B
print(np.shape(C))
print(np.linalg.matrix_rank(C))

# generalize to m*n rank-r
m = 8
n = 47
r = 3
A = np.random.randn(m, r)@np.random.randn(r, n)
print(np.shape(A))
print(np.linalg.matrix_rank(A))


(10, 10)
4
(8, 47)
3


In [30]:
# Code challenge - test whether the matrix rank is invariant to to scalar multiplication

m = 6
n = 4

F = np.random.randn(m, n)@np.random.randn(n, n)
R = np.random.randn(m, n-1)@np.random.randn(n-1, n)

print('Rank of full matrix: {}'.format(np.linalg.matrix_rank(F)))
print('Rank of reduced matrix: {}'.format(np.linalg.matrix_rank(R)))

l = 267353. # Scalar
print('Rank of scaled full matrix: {}'.format(np.linalg.matrix_rank(l*F)))
print('Rank of scaled reduced matrix: {}'.format(np.linalg.matrix_rank(l*R)))

# Scalar multiplication has no effect on rank, doesn't change the dimensionality except the scalar zero

Rank of full matrix: 4
Rank of reduced matrix: 3
Rank of scaled full matrix: 4
Rank of scaled reduced matrix: 3


In [32]:
# rank(A) = rank(AA.T) = rank(A.T) = rank(A.TA)

m = 14
n = 3

A = np.round(10*np.random.randn(m, n))
AtA = A.T@A
AAt = A@A.T

print(np.linalg.matrix_rank(AtA), np.linalg.matrix_rank(AAt), np.linalg.matrix_rank(A), np.linalg.matrix_rank(A.T))

3 3 3 3


In [34]:
# Making full-rank matrix by shifting

m = 30

# Create the square symmetrix matrix
A = np.random.randn(m, m)
A = np.round(10*A.T@A)

#reduce the rank
A[:, 0] = A[:, 1]

#shift amount
l = .01

B = A + l*np.eye(m)

print('Rank wihtout shift: {}'.format(np.linalg.matrix_rank(A)))
print('Rank with shift: {}'.format(np.linalg.matrix_rank(B)))

Rank wihtout shift: 29
Rank with shift: 30


In [51]:
# Determine whether vector is in span of set

v = np.array([[1, 2, 3, 4]]).T
print(v), print('')  #column vector

S = np.vstack(([4, 3, 6, 2], [0, 4, 0, 1])).T
T = np.vstack(([1, 2, 2, 2], [0, 0, 1, 2])).T
print(S), print('')
print(T), print('')
print(np.linalg.matrix_rank(S))
print(np.linalg.matrix_rank(T))

Sv = np.concatenate((S, v), axis = 1)
Tv = np.concatenate((T, v), axis = 1)
print(Sv), print('')
print(Tv), print('')

print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

# Since augmenting vector increases the rank of S, hence it is not in span of set S
# v is in the set of span T as the rank remains the same

[[1]
 [2]
 [3]
 [4]]

[[4 0]
 [3 4]
 [6 0]
 [2 1]]

[[1 0]
 [2 0]
 [2 1]
 [2 2]]

2
2
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]

3
2
